# We do not use sudo
sudo: false

# Python versions for matrix
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Django versions for matrix
env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.10'
  - DJANGO_VERSION='>=1.10,<1.11'
  - DJANGO_VERSION='>=1.11,<1.12'

# Command to install dependencies, e.g. pip install -r requirements.txt
install:
  - pip install Django$DJANGO_VERSION
  # Coverage 4.0 no longer supports py32. Install an older version before
  # coveralls tries to install the latest
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then travis_retry pip install 'coverage<4.0'; fi
  - pip install -r requirements.txt
  - pip install coveralls

# Command to run tests, e.g. python setup.py test
script:
  - coverage run --source=boilerplate manage.py test

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-1.11 }
    - { python: 3.4, env: TOXENV=py34-1.11 }
    - { python: 3.4, env: TOXENV=py34-2.0 }
    - { python: 3.5, env: TOXENV=py35-1.11 }
    - { python: 3.5, env: TOXENV=py35-2.0 }
    - { python: 3.5, env: TOXENV=py35-2.1 }
    - { python: 3.5, env: TOXENV=py35-2.2 }
    - { python: 3.5, env: TOXENV=py35-master }
    - { python: 3.6, env: TOXENV=py36-2.0 }
    - { python: 3.6, env: TOXENV=py36-2.1 }
    - { python: 3.6, env: TOXENV=py36-2.2 }
    - { python: 3.6, env: TOXENV=py36-master }
    - { python: 3.7, env: TOXENV=py37-2.1 }
    - { python: 3.7, env: TOXENV=py37-2.2 }
    - { python: 3.7, env: TOXENV=py37-master }
    - { python: 3.6, env: TOXENV=docs }
    - { python: 3.6, env: TOXENV=flake8 }

# Report to coveralls
after_success:
  - coveralls
